server:
  port: 9020

spring:
  application:
    name: enjoytix-performance-service
  mvc:
    problemdetails:
      enabled: true
  cloud:
    nacos:
      discovery:
        enabled: ${ENJOYTIX_NACOS_ENABLED:true}
        server-addr: ${ENJOYTIX_NACOS_SERVER_ADDR:127.0.0.1:8848}
        fail-fast: false
      config:
        enabled: ${ENJOYTIX_NACOS_ENABLED:true}
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        import-check:
          enabled: false

rocketmq:
  producer:
    group: ${spring.application.name}-producer

performance:
  sale-message:
    topic: enjoytix_performance_sale_start
    consumer-group: enjoytix_performance_sale_start_cg
    send-timeout-millis: 3000
    max-reconsume-times: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
