server:
  port: 9030

spring:
  application:
    name: enjoytix-ticket-service
  mvc:
    problemdetails:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        import-check:
          enabled: false

ticket:
  lock:
    ttl-minutes: 15

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
