server:
  port: 9000

spring:
  application:
    name: enjoytix-gateway-service
  webflux:
    problemdetails:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8686
        port: 8719
    gateway:
      routes:
        - id: enjoytix-user-service
          uri: lb://enjoytix-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user/me
                  - /api/user/attendees
                  - /api/user/addresses
                  - /api/user/orders
                  - /api/user/logout
        - id: enjoytix-performance-service
          uri: lb://enjoytix-performance-service
          predicates:
            - Path=/api/performance/**,/api/show/**,/api/venue/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/performance/admin
        - id: enjoytix-ticket-service
          uri: lb://enjoytix-ticket-service
          predicates:
            - Path=/api/ticket/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ticket/lock
                  - /api/ticket/release
                  - /api/ticket/issue
        - id: enjoytix-order-service
          uri: lb://enjoytix-order-service
          predicates:
            - Path=/api/order/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/order
        - id: enjoytix-pay-service
          uri: lb://enjoytix-pay-service
          predicates:
            - Path=/api/pay/**,/api/refund/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/pay
                  - /api/refund
        - id: enjoytix-marketing-service
          uri: lb://enjoytix-marketing-service
          predicates:
            - Path=/api/marketing/**
        - id: enjoytix-comment-service
          uri: lb://enjoytix-comment-service
          predicates:
            - Path=/api/comment/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/comment
        - id: enjoytix-user-service-openapi
          uri: lb://enjoytix-user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs/enjoytix-api
        - id: enjoytix-performance-service-openapi
          uri: lb://enjoytix-performance-service
          predicates:
            - Path=/v3/api-docs/performance-service
          filters:
            - RewritePath=/v3/api-docs/performance-service, /v3/api-docs/enjoytix-api
        - id: enjoytix-ticket-service-openapi
          uri: lb://enjoytix-ticket-service
          predicates:
            - Path=/v3/api-docs/ticket-service
          filters:
            - RewritePath=/v3/api-docs/ticket-service, /v3/api-docs/enjoytix-api
        - id: enjoytix-order-service-openapi
          uri: lb://enjoytix-order-service
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs/enjoytix-api
        - id: enjoytix-pay-service-openapi
          uri: lb://enjoytix-pay-service
          predicates:
            - Path=/v3/api-docs/pay-service
          filters:
            - RewritePath=/v3/api-docs/pay-service, /v3/api-docs/enjoytix-api
        - id: enjoytix-comment-service-openapi
          uri: lb://enjoytix-comment-service
          predicates:
            - Path=/v3/api-docs/comment-service
          filters:
            - RewritePath=/v3/api-docs/comment-service, /v3/api-docs/enjoytix-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: performance-service
        url: /v3/api-docs/performance-service
      - name: ticket-service
        url: /v3/api-docs/ticket-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: pay-service
        url: /v3/api-docs/pay-service
      - name: comment-service
        url: /v3/api-docs/comment-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
